apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-hao-setting
spec:
  forms:
    - group: nav
      label: 导航栏
      formSchema:
        - $formkit: text
          name: left_menu
          label: 导航栏左侧相关链接
          placeholder: 请填写 metadata name
          help: "需要通过开发者模式获取菜单对应的 metadata name"
        - $formkit: radio
          name: right_menu
          label: 右侧四个按钮
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: text
          name: site_title
          label: 标题
          placeholder: 请输入标题
          help: 支持 HTML 语法，比如 <span id="site-name-icon">Hao</span>，默认为站点名称
    - group: top
      label: 顶部
      formSchema:
        - $formkit: radio
          name: recent_top
          label: 首页顶部
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: radio
          name: time_list
          label: 日志模块
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: text
          name: banners_title_big
          label: Banners 大标题
          placeholder: 请输入大标题
          help: 支持 HTML 语法
        - $formkit: text
          name: banners_title_small
          label: Banners 小标题
          placeholder: 请输入小标题
          help: 支持 HTML 语法
    - group: layout
      label: 布局
      formSchema:
        - $formkit: select
          name: post_list_layout
          label: 文章列表布局
          value: grid_3
          options:
            - label: 网格（一行三列）
              value: grid_3
            - label: 网格（一行两列）
              value: grid_2
            - label: 单条
              value: single
          help: "选择单条时，文章卡片的图片将位于左侧"
        - $formkit: select
          name: header_widget
          label: 首页顶部模块
          value: none
          options:
            - label: 无
              value: none
            - label: 最新一篇文章
              value: latest_post
            - label: 文章网格（最新五篇文章）
              value: latest_post_grid
            - label: 轮播图
              value: carousel
            - label: 站点标题
              value: site_title
        - $formkit: select
          name: header_background_type
          label: 首页顶部背景
          value: manual
          options:
            - label: 手动设置
              value: manual
            - label: 图片
              value: image
        - $formkit: text
          name: header_background
          label: 首页顶部背景
        - $formkit: text
          name: header_background_image
          label: 首页顶部背景图片
        - $formkit: radio
          name: content_header
          label: 文章页顶部
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
    - group: sidebar
      label: 侧边栏
      formSchema:
        - $formkit: textarea
          name: widgets
          label: 小部件
          value: "profile,popular-posts,latest-comments,categories,tags"
          help: "目前提供的小部件有：profile（站点资料）, popular-posts（热门文章）, latest-comments（最新评论）, categories（文章分类）, tags（文章标签）。你可以随意组合或排序，以逗号隔开。"
        - $formkit: text
          name: profile_name
          label: 个人卡片名称
          placeholder: 请填写个人卡片名称
          help: "不填写默认为站点则名称"
        - $formkit: textarea
          name: profile_desc
          placeholder: 请填写个人卡片描述信息
          help: "支持使用 HTML 标签"
    - group: footer
      label: 页脚
      formSchema:
        - $formkit: text
          name: menu
          label: 底部相关链接
          placeholder: 请填写 metadata name
          help: "需要通过开发者模式获取菜单对应的 metadata name"
    - group: loading
      label: 加载页
      formSchema:
        - $formkit: radio
          name: switch
          label: 开关
          value: true
          options:
            - label: 打开
              value: true
            - label: 关闭
              value: false
        - $formkit: url
          name: img
          validation: "url"
          label: 加载页图片 URL
          placeholder: 请输入图片 url
    - group: right_menu
      label: 右键菜单
      formSchema:
        - $formkit: radio
          name: switch
          label: 开关
          value: true
          options:
            - label: 打开
              value: true
            - label: 关闭
              value: false